controller_server:
  ros__parameters:
    acc_lim_x: 2.5
    acc_lim_theta: 3.2
    transform_tolerance: 1.0
    use_sim_time: True
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    controller_frequency: 10.0
    controller_plugins: ["FollowPath"]
    progress_checker_plugin: "progress_checker"
    goal_checker_plugin: "general_goal_checker"
    curent_goal_checker: "general_goal_checker"

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 100.0

    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25

    FollowPath:
      use_sim_time: true
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: True
      min_vel_x: 0.0
      min_vel_y: 0.0
      max_vel_x: 1.0
      max_vel_y: 0.0
      max_vel_theta: 1.0
      min_vel_theta: -1.0
      min_speed_xy: 0.0
      max_speed_xy: 2.0
      min_speed_theta: 0.0
      acc_lim_x: 2.5
      acc_lim_y: 0.0
      acc_lim_theta: 3.2
      decel_lim_x: -2.5
      decel_lim_y: 0.0
      decel_lim_theta: -3.2
      vx_samples: 50
      vy_samples: 0
      vtheta_samples: 50
      sim_time: 1.5
      linear_granularity: 0.5
      angular_granularity: 0.025
      transform_tolerance: 0.2
      xy_goal_tolerance: 0.25
      trans_stopped_velocity: 0.25
      short_circuit_trajectory_evaluation: False

      critics: ["Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist", "RotateToGoal"]
      
      # Конфигурация каждого критика
      Oscillation:
        plugin: "dwb_critics::OscillationCritic"
        oscillation_reset_dist: 0.05
        oscillation_reset_angle: 0.1
        
      BaseObstacle:
        plugin: "dwb_critics::ObstacleFootprintCritic"
        scale: 1.0         # Сила влияния препятствий
        inflation_cost_scaling_factor: 5.0
        
      GoalAlign:
        plugin: "dwb_critics::GoalAlignCritic"
        scale: 24.0
        forward_point_distance: 0.1
        max_angle: 0.785   # 45 градусов в радианах
        
      PathAlign:
        plugin: "dwb_critics::PathAlignCritic"
        scale: 50.0
        forward_point_distance: 0.1
        
      PathDist:
        plugin: "dwb_critics::PathDistCritic"
        scale: 100.0
        
      GoalDist:
        plugin: "dwb_critics::GoalDistCritic"
        scale: 10.0
        
      RotateToGoal:
        plugin: "dwb_critics::RotateToGoalCritic"
        scale: 64.0
        slowing_factor: 1.0
        lookahead_time: -1.0 


planner_server:
  ros__parameters:
    use_sim_time: true
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.25
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.1
      max_planning_duration: 5.0
      use_astar: false
      allow_unknown: true

bt_navigator:
  ros__parameters:
    use_sim_time: true
    global_frame: map
    robot_base_frame: base_link
    odom_topic: odom
    bt_loop_duration: 10
    filter_duration: 0.3
    navigators: ["navigate_to_pose", "navigate_through_poses"]
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator"
    navigate_through_poses:
      plugin: "nav2_bt_navigator::NavigateThroughPosesNavigator"

local_costmap:
  local_costmap:
    ros__parameters:
      transform_tolerance: 1.0  
      inflation_radius: 0.5
      always_send_full_costmap: true
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: true
      rolling_window: true
      width: 5
      height: 5
      resolution: 0.05
      footprint: "[[0.25, 0.2], [0.25, -0.2], [-0.25, -0.2], [-0.25, 0.2]]"
      footprint_padding: 0.01
      plugins: ["obstacle_layer", "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: /base_scan
          max_obstacle_height: 2.0
          clearing: true
          marking: true
          data_type: LaserScan

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.5

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True

global_costmap:
  global_costmap:
    ros__parameters:
      transform_tolerance: 1.0
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: true
      width: 10
      height: 10
      resolution: 0.05
      footprint: "[[0.25, 0.2], [0.25, -0.2], [-0.25, -0.2], [-0.25, 0.2]]"
      footprint_padding: 0.01
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_topic: "/map"
        map_subscribe_transient_local: true 

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: /base_scan
          max_obstacle_height: 2.0
          clearing: true
          marking: true
          data_type: LaserScan

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.5
