slam_toolbox:
  ros__parameters:
    base_frame: "base_link"
    map_frame: "map"
    odom_frame: "odom"
    scan_topic: "/base_scan"

    mode: "mapping"

    resolution: 0.05
    max_laser_range: 5.0
    
    particles: 20
    map_update_interval: 1.0
    throttle_scans: 1
    transform_publish_period: 0.1
